- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: apic
  connection: local
  gather_facts: False
  vars_prompt:
    - name: "epg"
      prompt: "What would you like to name your EPG?"
      private: no

  tasks:
    - name: Add a new EPG
      aci_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        tenant: JR_test_TEN
        ap: JR_test_AP
        epg: "{{ epg }}"
        description: Web Intranet EPG
        bd: JR_test_BD
        monitoring_policy: default
        preferred_group: yes
        state: present
      delegate_to: localhost
